# -*- coding: utf-8 -*-
"""Hm1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XACC-ljhieScDa66nXtm6Larg5LWrjfp
"""

import numpy as np
a = np.arange(1, 11)
print(a)

import numpy as np
a = np.zeros((3, 3))
print(a)

import numpy as np
a = np.random.randint(1, 11, size=(5, 5))
print(a)

import numpy as np
a = np.random.rand(4, 4)
print(a)

import numpy as np
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
addition = a + b
subtraction = a - b
multiplication = a * b
print(addition)
print(subtraction)
print(multiplication)

import numpy as np
a = np.random.rand(7)
b = np.random.rand(7)
print(np.dot(a, b))

import numpy as np
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
print(np.dot(a, b))

import numpy as np
a = np.random.randint(1, 11, size=(3, 3))
print(np.linalg.inv(a))

import numpy as np
a = np.random.rand(4, 4)
print(a.T)

import numpy as np
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
print(np.dot(a, b))

import numpy as np
a = np.random.rand(2, 3)
b = np.random.rand(3)
print(np.dot(a, b))

import numpy as np
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a*b)

import numpy as np
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(np.dot(a, b))

import numpy as np
a = np.random.randint(1, 101, size=(5, 5))
print(np.sum(a))

import numpy as np
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print(a-b)

import numpy as np
a = np.random.rand(3, 3)
row_sums = np.sum(a, axis=1)
column_vector = row_sums.reshape(-1, 1)
print(column_vector)

import numpy as np
a = np.random.randint(1, 11, size=(3, 4))
print(np.square(a))

import numpy as np
a = np.random.randint(1, 51, size=4)
print(np.sqrt(a))